/* tslint:disable */
/* eslint-disable */
/**
 * YT-DLP-Web-App-Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  UsedStorageResponse,
} from '../models/index';
import {
    UsedStorageResponseFromJSON,
    UsedStorageResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class StorageApi extends runtime.BaseAPI {

    /**
     */
    async apiStorageGetUsedStorageGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsedStorageResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Storage/GetUsedStorage`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UsedStorageResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiStorageGetUsedStorageGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsedStorageResponse> {
        const response = await this.apiStorageGetUsedStorageGetRaw(initOverrides);
        return await response.value();
    }

}
