/* tslint:disable */
/* eslint-disable */
/**
 * YT-DLP-Web-App-Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChapterData
 */
export interface ChapterData {
    /**
     * 
     * @type {number}
     * @memberof ChapterData
     */
    startTime?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ChapterData
     */
    endTime?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ChapterData
     */
    title?: string | null;
}

/**
 * Check if a given object implements the ChapterData interface.
 */
export function instanceOfChapterData(value: object): value is ChapterData {
    return true;
}

export function ChapterDataFromJSON(json: any): ChapterData {
    return ChapterDataFromJSONTyped(json, false);
}

export function ChapterDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChapterData {
    if (json == null) {
        return json;
    }
    return {
        
        'startTime': json['startTime'] == null ? undefined : json['startTime'],
        'endTime': json['endTime'] == null ? undefined : json['endTime'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function ChapterDataToJSON(value?: ChapterData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'startTime': value['startTime'],
        'endTime': value['endTime'],
        'title': value['title'],
    };
}

