/* tslint:disable */
/* eslint-disable */
/**
 * YT-DLP-Web-App-Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MaybeBool = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type MaybeBool = typeof MaybeBool[keyof typeof MaybeBool];


export function instanceOfMaybeBool(value: any): boolean {
    for (const key in MaybeBool) {
        if (Object.prototype.hasOwnProperty.call(MaybeBool, key)) {
            if (MaybeBool[key as keyof typeof MaybeBool] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MaybeBoolFromJSON(json: any): MaybeBool {
    return MaybeBoolFromJSONTyped(json, false);
}

export function MaybeBoolFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaybeBool {
    return json as MaybeBool;
}

export function MaybeBoolToJSON(value?: MaybeBool | null): any {
    return value as any;
}

