/* tslint:disable */
/* eslint-disable */
/**
 * YT-DLP-Web-App-Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MetadataType = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4
} as const;
export type MetadataType = typeof MetadataType[keyof typeof MetadataType];


export function instanceOfMetadataType(value: any): boolean {
    for (const key in MetadataType) {
        if (Object.prototype.hasOwnProperty.call(MetadataType, key)) {
            if (MetadataType[key as keyof typeof MetadataType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MetadataTypeFromJSON(json: any): MetadataType {
    return MetadataTypeFromJSONTyped(json, false);
}

export function MetadataTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetadataType {
    return json as MetadataType;
}

export function MetadataTypeToJSON(value?: MetadataType | null): any {
    return value as any;
}

