/* tslint:disable */
/* eslint-disable */
/**
 * YT-DLP-Web-App-Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OrderVideosBy = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type OrderVideosBy = typeof OrderVideosBy[keyof typeof OrderVideosBy];


export function instanceOfOrderVideosBy(value: any): boolean {
    for (const key in OrderVideosBy) {
        if (Object.prototype.hasOwnProperty.call(OrderVideosBy, key)) {
            if (OrderVideosBy[key as keyof typeof OrderVideosBy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OrderVideosByFromJSON(json: any): OrderVideosBy {
    return OrderVideosByFromJSONTyped(json, false);
}

export function OrderVideosByFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderVideosBy {
    return json as OrderVideosBy;
}

export function OrderVideosByToJSON(value?: OrderVideosBy | null): any {
    return value as any;
}

