/* tslint:disable */
/* eslint-disable */
/**
 * YT-DLP-Web-App-Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubtitleData
 */
export interface SubtitleData {
    /**
     * 
     * @type {string}
     * @memberof SubtitleData
     */
    ext?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SubtitleData
     */
    data?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SubtitleData
     */
    url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SubtitleData
     */
    name?: string | null;
}

/**
 * Check if a given object implements the SubtitleData interface.
 */
export function instanceOfSubtitleData(value: object): value is SubtitleData {
    return true;
}

export function SubtitleDataFromJSON(json: any): SubtitleData {
    return SubtitleDataFromJSONTyped(json, false);
}

export function SubtitleDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubtitleData {
    if (json == null) {
        return json;
    }
    return {
        
        'ext': json['ext'] == null ? undefined : json['ext'],
        'data': json['data'] == null ? undefined : json['data'],
        'url': json['url'] == null ? undefined : json['url'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function SubtitleDataToJSON(value?: SubtitleData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ext': value['ext'],
        'data': value['data'],
        'url': value['url'],
        'name': value['name'],
    };
}

