/* tslint:disable */
/* eslint-disable */
/**
 * YT-DLP-Web-App-Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoDuration
 */
export interface VideoDuration {
    /**
     * 
     * @type {string}
     * @memberof VideoDuration
     */
    startTime?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoDuration
     */
    endTime?: string | null;
}

/**
 * Check if a given object implements the VideoDuration interface.
 */
export function instanceOfVideoDuration(value: object): value is VideoDuration {
    return true;
}

export function VideoDurationFromJSON(json: any): VideoDuration {
    return VideoDurationFromJSONTyped(json, false);
}

export function VideoDurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoDuration {
    if (json == null) {
        return json;
    }
    return {
        
        'startTime': json['startTime'] == null ? undefined : json['startTime'],
        'endTime': json['endTime'] == null ? undefined : json['endTime'],
    };
}

export function VideoDurationToJSON(value?: VideoDuration | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'startTime': value['startTime'],
        'endTime': value['endTime'],
    };
}

