/* tslint:disable */
/* eslint-disable */
/**
 * YT-DLP-Web-App-Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoDownloadInfo
 */
export interface VideoDownloadInfo {
    /**
     * 
     * @type {number}
     * @memberof VideoDownloadInfo
     */
    videoId?: number;
    /**
     * 
     * @type {number}
     * @memberof VideoDownloadInfo
     */
    downloadPercent?: number;
    /**
     * 
     * @type {boolean}
     * @memberof VideoDownloadInfo
     */
    downloaded?: boolean;
}

/**
 * Check if a given object implements the VideoDownloadInfo interface.
 */
export function instanceOfVideoDownloadInfo(value: object): value is VideoDownloadInfo {
    return true;
}

export function VideoDownloadInfoFromJSON(json: any): VideoDownloadInfo {
    return VideoDownloadInfoFromJSONTyped(json, false);
}

export function VideoDownloadInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoDownloadInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'videoId': json['videoId'] == null ? undefined : json['videoId'],
        'downloadPercent': json['downloadPercent'] == null ? undefined : json['downloadPercent'],
        'downloaded': json['downloaded'] == null ? undefined : json['downloaded'],
    };
}

export function VideoDownloadInfoToJSON(value?: VideoDownloadInfo | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'videoId': value['videoId'],
        'downloadPercent': value['downloadPercent'],
        'downloaded': value['downloaded'],
    };
}

