/* tslint:disable */
/* eslint-disable */
/**
 * YT-DLP-Web-App-Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoDimensions
 */
export interface VideoDimensions {
    /**
     * 
     * @type {number}
     * @memberof VideoDimensions
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof VideoDimensions
     */
    height?: number;
}

/**
 * Check if a given object implements the VideoDimensions interface.
 */
export function instanceOfVideoDimensions(value: object): value is VideoDimensions {
    return true;
}

export function VideoDimensionsFromJSON(json: any): VideoDimensions {
    return VideoDimensionsFromJSONTyped(json, false);
}

export function VideoDimensionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoDimensions {
    if (json == null) {
        return json;
    }
    return {
        
        'width': json['width'] == null ? undefined : json['width'],
        'height': json['height'] == null ? undefined : json['height'],
    };
}

export function VideoDimensionsToJSON(value?: VideoDimensions | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'width': value['width'],
        'height': value['height'],
    };
}

