/* tslint:disable */
/* eslint-disable */
/**
 * YT-DLP-Web-App-Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoNameResponse
 */
export interface VideoNameResponse {
    /**
     * 
     * @type {string}
     * @memberof VideoNameResponse
     */
    name?: string | null;
}

/**
 * Check if a given object implements the VideoNameResponse interface.
 */
export function instanceOfVideoNameResponse(value: object): value is VideoNameResponse {
    return true;
}

export function VideoNameResponseFromJSON(json: any): VideoNameResponse {
    return VideoNameResponseFromJSONTyped(json, false);
}

export function VideoNameResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoNameResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function VideoNameResponseToJSON(value?: VideoNameResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

