/* tslint:disable */
/* eslint-disable */
/**
 * YT-DLP-Web-App-Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoCountResponse
 */
export interface VideoCountResponse {
    /**
     * 
     * @type {number}
     * @memberof VideoCountResponse
     */
    count?: number;
}

/**
 * Check if a given object implements the VideoCountResponse interface.
 */
export function instanceOfVideoCountResponse(value: object): value is VideoCountResponse {
    return true;
}

export function VideoCountResponseFromJSON(json: any): VideoCountResponse {
    return VideoCountResponseFromJSONTyped(json, false);
}

export function VideoCountResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoCountResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
    };
}

export function VideoCountResponseToJSON(value?: VideoCountResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
    };
}

